# Generated by Django 3.1.4 on 2020-12-17 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cik', models.CharField(max_length=10)),
                ('description', models.TextField(default='', null=True)),
                ('focus', models.CharField(default='', max_length=128)),
                ('trust_size', models.IntegerField()),
                ('ipo_date', models.DateField(default=datetime.datetime.now)),
                ('merger_deadline', models.DateField(default=datetime.datetime.now)),
                ('target_company', models.CharField(default='', max_length=128)),
                ('shares_redeemed', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('P', 'PreIPO'), ('TS', 'Searching for target'), ('TF', 'Target found'), ('M', 'Merge complete')], default='P', max_length=2)),
                ('auditor', models.ManyToManyField(to='companies.Auditor')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SECFormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_ticker_symbol', models.CharField(max_length=8)),
                ('common_qty', models.PositiveIntegerField(default=0)),
                ('preferred_qty', models.PositiveIntegerField()),
                ('unit_ticker_symbol', models.CharField(max_length=8)),
                ('unit_qty', models.PositiveIntegerField()),
                ('unit_common_total', models.PositiveSmallIntegerField()),
                ('unit_warrant_total', models.PositiveSmallIntegerField()),
                ('warrant_ticker_symbol', models.CharField(max_length=8)),
                ('warrant_qty', models.PositiveIntegerField()),
                ('warrant_ratio_antecedent', models.PositiveIntegerField()),
                ('warrant_ratio_consequent', models.PositiveIntegerField()),
                ('warrant_redemption_price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('rights_ticker_symbol', models.CharField(max_length=8)),
                ('rights_qty', models.PositiveIntegerField()),
                ('rights_redemption_price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Underwriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('L', 'Lead Left'), ('S', 'Sole'), ('J', 'Joint')], max_length=1)),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('valuation', models.BigIntegerField()),
                ('country', models.CharField(max_length=128)),
                ('industry', models.ManyToManyField(to='companies.Industry')),
                ('sector', models.ManyToManyField(to='companies.Sector')),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='SECFilings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2083)),
                ('date_filed', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('form_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.secformtype')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('current_member', models.BooleanField()),
                ('profile', models.TextField()),
                ('hire_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('U', 'Underwriter'), ('I', 'Issuer'), ('F', 'Foreign')], max_length=1)),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Items8K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=256)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.secfilings')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(to='companies.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal',
            field=models.ManyToManyField(to='companies.Legal'),
        ),
        migrations.AddField(
            model_name='company',
            name='management',
            field=models.ManyToManyField(to='companies.Management'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ManyToManyField(to='companies.Sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='shares',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.shares'),
        ),
        migrations.AddField(
            model_name='company',
            name='social_media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='social_media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia'),
        ),
    ]
