# Generated by Django 3.1.4 on 2020-12-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shares',
        ),
        migrations.AddField(
            model_name='company',
            name='common_qty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='common_ticker_symbol',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='preferred_qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_redemption_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_ticker_symbol',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_common_total',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_ticker_symbol',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_warrant_total',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_ratio_antecedent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_ratio_consequent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_redemption_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_ticker_symbol',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
