# Generated by Django 3.1.4 on 2020-12-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20201218_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='social_media',
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ipo_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='merger_deadline',
            field=models.DateField(null=True),
        ),
    ]
