# Generated by Django 3.1.5 on 2020-12-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20201218_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secfilings',
            name='form_type',
        ),
        migrations.AddField(
            model_name='secfilings',
            name='filing_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='secfilings',
            name='form_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='secfilings',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='secfilings',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Items8K',
        ),
        migrations.DeleteModel(
            name='SECFormType',
        ),
    ]
