# Generated by Django 3.1.5 on 2020-12-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20201220_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('P', 'PreIPO'), ('S', 'Searching for target'), ('F', 'Found target'), ('M', 'Merge complete')], default='P', max_length=2),
        ),
    ]
