# Generated by Django 3.1.5 on 2020-12-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20201220_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='focus',
            field=models.TextField(default='', null=True),
        ),
    ]
