# Generated by Django 3.1.5 on 2020-12-20 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20201220_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('earnings_indicator', models.CharField(max_length=32)),
                ('revenue', models.CharField(max_length=16)),
                ('earnings', models.CharField(max_length=16)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Shares',
        ),
        migrations.RemoveField(
            model_name='targetcompany',
            name='valuation',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='secfilings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secfilings',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='enterprise_valuation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='equity_valuation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='investor_presentation',
            field=models.URLField(max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='pipe_size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='futureearnings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.targetcompany'),
        ),
    ]
