# Generated by Django 3.1.5 on 2021-01-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20210109_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128)),
                ('enterprise_valuation', models.PositiveSmallIntegerField(default=0)),
                ('equity_valuation', models.PositiveSmallIntegerField(default=0)),
                ('pipe_size', models.PositiveSmallIntegerField(null=True)),
                ('investor_presentation', models.URLField(max_length=2083, null=True)),
                ('industry', models.ManyToManyField(to='companies.Industry')),
                ('sector', models.ManyToManyField(to='companies.Sector')),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='FutureEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('earnings_indicator', models.CharField(max_length=32)),
                ('revenue', models.CharField(max_length=16)),
                ('earnings', models.CharField(max_length=16)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.targetcompany')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.targetcompany'),
        ),
    ]
