# Generated by Django 3.1.5 on 2021-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20210114_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secfilings',
            name='form_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
