# Generated by Django 3.1.5 on 2021-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20210117_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secfilings',
            name='date_filed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
