# Generated by Django 3.1.5 on 2021-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20210117_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secfilings',
            name='form_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='secfilings',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
