# Generated by Django 3.1.5 on 2021-01-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20210117_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futureearnings',
            old_name='company',
            new_name='target_company',
        ),
    ]
