# Generated by Django 3.1.5 on 2021-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcompany',
            name='about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='employees',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='founded',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='headquarters',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.RemoveField(
            model_name='targetcompany',
            name='industry',
        ),
        migrations.AddField(
            model_name='targetcompany',
            name='industry',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
