# Generated by Django 3.1.5 on 2021-02-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20210228_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='social_media',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.socialmedia'),
        ),
    ]
