# Generated by Django 3.1.5 on 2021-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20210228_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='role',
            field=models.CharField(max_length=128),
        ),
    ]
