# Generated by Django 3.1.5 on 2021-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_auto_20210228_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='common_price',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_price',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_price',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_price',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
