# Generated by Django 3.1.5 on 2021-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20210301_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='common_price',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rights_price',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='unit_price',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='warrant_price',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
