# Generated by Django 3.1.5 on 2021-03-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20210302_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change_perc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RightsQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change_perc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change_perc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change_perc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='common_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.commonquote'),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.rightsquote'),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.unitquote'),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.warrantquote'),
        ),
    ]
