# Generated by Django 3.1.5 on 2021-03-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20210302_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonquote',
            old_name='company',
            new_name='common',
        ),
    ]
