# Generated by Django 3.1.5 on 2021-03-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_auto_20210302_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rights_quote',
        ),
        migrations.RemoveField(
            model_name='company',
            name='warrant_quote',
        ),
        migrations.AddField(
            model_name='rightsquote',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='warrantquote',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
