# Generated by Django 3.1.7 on 2021-04-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_auto_20210302_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='secfilings',
            name='accession_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
