# Generated by Django 3.1.7 on 2021-04-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_auto_20210401_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='common_change',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='common_change_perc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='common_volume',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_change',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_change_perc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_volume',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_change',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_change_perc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_volume',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_change',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_change_perc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_volume',
            field=models.CharField(max_length=16, null=True),
        ),
    ]