# Generated by Django 3.1.7 on 2021-04-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20210401_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='common_price',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rights_price',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_price',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='warrant_price',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
