# Generated by Django 3.1.7 on 2021-04-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_auto_20210401_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trust_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
