# Generated by Django 3.2.2 on 2021-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_auto_20210411_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetcompany',
            name='enterprise_valuation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='targetcompany',
            name='equity_valuation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
